library("rJava")
library("RWeka")
library("RWekajars")
#library("Rgraphviz")
#library("MASS")
#library("slam")
#library("igraph")
library("wordnet")
wordnet::getDict()
interestingList <- as.list(synonyms('prevarication', pos='VERB'))
synonyms('betray', pos='VERB')
synonyms('prevaricate', pos='VERB')
resultPrevarication <- synonyms('cheat', pos='VERB')
mode(resultPrevarication)
greenspan <- function(x) { synonyms(x, pos='VERB') }
gr<-as.list(resultPrevarication)
lapply(gr, greenspan)
RecGreenspan <- function(x) { if (length(x) > 1) { break }
x <- synonyms(x, pos='VERB')
x<-as.list(x)
#RecGreenspan(x)
#print('#######################')
#print(length(x))
print(x)
#x<-lapply(x, RecGreenspan)
#print('#######################')
#return(x)
}
a<-RecGreenspan('betray')
a
unlist(a)
